export type Lang = "th" | "en";

export const COPY = {
  th: {
    tagline: "ห้องบัญชาการเอเจนต์บน Grok พร้อมโหมดสร้างและแซนด์บ็อกซ์",
    loginLead: "BossnuGrok ใช้ Grok ของ xAI เป็นแกนหลัก ล็อกอิน Puter เป็นทางเลือกสำหรับโมเดลอื่น",
    continuePuter: "เชื่อม Puter สำหรับโมเดลอื่น",
    waitingPuter: "กำลังรอหน้าต่าง Puter…",
    connecting: "กำลังเชื่อม…",
    retryPuter: "ลองเชื่อม Puter อีกครั้ง",
    popupHint: "Puter เป็นทางเลือก อนุญาตป๊อปอัปถ้าต้องการโมเดลนอก Grok",
    signOut: "ตัดการเชื่อม Puter",
    guest: "ผู้เยี่ยมชม",
    forge: "โรงงาน",
    registry: "ทะเบียนเอเจนต์",
    channel: "ช่องสื่อสาร",
    forgeCta: "หล่อเอเจนต์",
    forging: "กำลังหล่อ…",
    role: "บทบาท",
    mission: "ภารกิจ",
    missionPh: "เช่น สร้างแบบฝึกหัดเศษส่วนสำหรับ ป.4 ที่ตรวจคำตอบได้อัตโนมัติ",
    constraints: "กฎเหล็ก (ไม่บังคับ)",
    constraintsPh: "บรรทัดละหนึ่งข้อ เช่น ห้ามใช้ศัพท์เทคนิค",
    emptyAgents: "ยังไม่มีเอเจนต์ย่อย หล่อตัวแรกจากโรงงาน",
    selectAgent: "เลือกเอเจนต์จากทะเบียนเพื่อเริ่มสื่อสาร",
    startChat: "เริ่มสนทนากับเอเจนต์…",
    send: "ส่ง",
    composePh: "สั่งการเอเจนต์ หรือแนบไฟล์…",
    retire: "ปลดระวาง",
    msgs: "ข้อความ",
    auto: "Grok อัตโนมัติ",
    model: "โมเดล",
    newChat: "แชทใหม่",
    thinking: "Grok กำลังคิด",
    noModels: "Grok ยังตอบไม่ได้ ลองอีกครั้ง",
    quota: "โควต้าเต็มแล้ว รอสักครู่แล้วลองใหม่",
    taskTooShort: "ภารกิจต้องยาวอย่างน้อย 10 ตัวอักษร",
    synced: "ซิงก์กับ Puter แล้ว",
    syncing: "กำลังซิงก์…",
    syncError: "ซิงก์ไม่สำเร็จ เก็บไว้เครื่องนี้",
    language: "ภาษา",
    emptyTitle: "ห้องว่าง",
    emptyBody: "คุยกับผู้บัญชาการ สร้างภาพ หรือเปิดแซนด์บ็อกซ์ได้เลย",
    suggest1: "สรุปภารกิจของคุณในสามบรรทัด",
    suggest2: "วางแผนงาน แล้วบอกว่าเอเจนต์บทบาทไหนควรรับช่วง",
    benefit1t: "Grok 4.5 เป็นแกนของทุกคำสั่ง",
    benefit1s: "xAI ในเซิร์ฟเวอร์ — ไม่ต้องวางคีย์ในเบราว์เซอร์",
    benefit2t: "โหมดสร้าง + แซนด์บ็อกซ์",
    benefit2s: "Imagine สร้างภาพ และรันโค้ดในกรอบที่แยกจากเครื่องคุณ",
    benefit3t: "ปลั๊กอินไฟล์และเอเจนต์",
    benefit3s: "แนบไฟล์ หล่อบทบาท คุยแยกประวัติ",
    developedBy: "พัฒนาโดย ภาณุพันธ์",
    modeCommand: "บัญชาการ",
    modeCreate: "สร้าง",
    modeSandbox: "แซนด์บ็อกซ์",
    modeLive: "สตรีมสด",
    modeTerminal: "เทอร์มินัล",
    modeSuper: "GrokSuper",
    createTitle: "โหมดสร้าง",
    createLead: "สั่ง Grok Imagine ให้วาดภาพจากข้อความ",
    createPh: "เช่น ห้องบัญชาการมืด หน้าจอเรืองแสงเหล็ก บรรยากาศเยือกเย็น",
    createCta: "สร้างภาพ",
    creating: "กำลังวาด…",
    createEmpty: "ยังไม่มีภาพ สั่งพรอมต์ด้านบนแล้วกดสร้าง",
    sandboxTitle: "แซนด์บ็อกซ์",
    sandboxLead: "รัน JavaScript ใน iframe ที่แยกจากเครื่อง — ไม่มีเครือข่าย",
    sandboxRun: "รัน",
    sandboxClear: "ล้าง",
    sandboxConsole: "คอนโซล",
    attach: "แนบไฟล์",
    attached: "ไฟล์ที่แนบ",
    plugins: "ปลั๊กอิน",
    pluginGrok: "Grok xAI",
    pluginImagine: "Imagine",
    pluginSandbox: "แซนด์บ็อกซ์",
    pluginFiles: "ไฟล์",
    toSandbox: "ส่งโค้ดไปแซนด์บ็อกซ์",
  },
  en: {
    tagline: "A Grok-powered agent command center with Create and Sandbox.",
    loginLead: "BossnuGrok runs on Grok from xAI. Puter is optional for extra models.",
    continuePuter: "Connect Puter for extra models",
    waitingPuter: "Waiting for Puter…",
    connecting: "Connecting…",
    retryPuter: "Retry Puter",
    popupHint: "Puter is optional. Allow popups only if you want models beyond Grok.",
    signOut: "Disconnect Puter",
    guest: "Guest",
    forge: "The Forge",
    registry: "Active agents",
    channel: "Channel",
    forgeCta: "Forge agent",
    forging: "Forging…",
    role: "Role",
    mission: "Mission",
    missionPh: "e.g. Draft fraction worksheets for grade 4 with auto-checked answers",
    constraints: "Hard rules (optional)",
    constraintsPh: "One per line, e.g. no jargon",
    emptyAgents: "No specialist agents yet. Forge the first one.",
    selectAgent: "Pick an agent from the registry to talk",
    startChat: "Start talking to this agent…",
    send: "Send",
    composePh: "Brief the agent, or attach a file…",
    retire: "Retire",
    msgs: "msgs",
    auto: "Grok auto",
    model: "Model",
    newChat: "New chat",
    thinking: "Grok is thinking",
    noModels: "Grok did not answer. Retry in a moment.",
    quota: "Quota hit. Wait, then retry.",
    taskTooShort: "Mission must be at least 10 characters",
    synced: "Synced to Puter",
    syncing: "Syncing…",
    syncError: "Sync failed — saved on this device",
    language: "Language",
    emptyTitle: "Quiet room",
    emptyBody: "Talk to the commander, create an image, or open the sandbox.",
    suggest1: "Summarise your mission in three lines",
    suggest2: "Plan the work and name which role should take each part",
    benefit1t: "Grok 4.5 is the core of every command",
    benefit1s: "xAI on the server — no keys in the browser",
    benefit2t: "Create mode + sandbox",
    benefit2s: "Imagine for images, and code that never touches your machine",
    benefit3t: "File plugin and agents",
    benefit3s: "Attach files, forge roles, keep histories separate",
    developedBy: "Built by Phanuphan",
    modeCommand: "Command",
    modeCreate: "Create",
    modeSandbox: "Sandbox",
    modeLive: "Live",
    modeTerminal: "Terminal",
    modeSuper: "GrokSuper",
    createTitle: "Create",
    createLead: "Ask Grok Imagine to draw from a prompt.",
    createPh: "e.g. a dark command room, steel glow on the screens, cold air",
    createCta: "Generate",
    creating: "Drawing…",
    createEmpty: "No images yet. Write a prompt and generate.",
    sandboxTitle: "Sandbox",
    sandboxLead: "Run JavaScript in a sealed iframe — no network.",
    sandboxRun: "Run",
    sandboxClear: "Clear",
    sandboxConsole: "Console",
    attach: "Attach file",
    attached: "Attached",
    plugins: "Plugins",
    pluginGrok: "Grok xAI",
    pluginImagine: "Imagine",
    pluginSandbox: "Sandbox",
    pluginFiles: "Files",
    toSandbox: "Send code to sandbox",
  },
} as const;
